pfsd:
  name: pfsd

  replicaCount: 1

  image:
    repository: gguiulfo/cloudserver
    tag: pfsd-3
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

rclone:
  name: rclone

  image:
    repository: gguiulfo/rclone
    tag: "1.0"
    pullPolicy: IfNotPresent

  schedule: "0 */12 * * *"
  successfulJobsHistory: 1

  remote:
    accessKey: my-access-key
    secretKey: my-secret-key
    endpoint: http://cloudserver
    region: pfsd-1
    bucket: pfsd-1

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

persistentVolume:
  server: 10.100.1.36
  path: /data
  accessModes:
    - ReadWriteMany
  size: 1Gi
