apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "cosmos.fullname" . }}
  labels:
    app: {{ template "cosmos.name" . }}
    chart: {{ template "cosmos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  accessModes:
{{- range .Values.persistentVolume.accessModes }}
    - {{ . | quote }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size | quote }}
  storageClassName: {{ template "cosmos.fullname" . }}
