kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cosmos-operator
rules:
- apiGroups:
  - zenko.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - "*"
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - persistentvolumes
  - events
  - jobs
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-cosmos-operator
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: cosmos-operator
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cosmos-operator
rules:
  - apiGroups: [""]
    resources:
    - persistentvolumeclaims
    - persistentvolumes
    verbs:
    - "*"
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs:
    - "*"
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-account-cosmos-operator
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cosmos-operator
  apiGroup: rbac.authorization.k8s.io
